### ISSUE TITLE
Merge with https://github.com/simonpasquier/prometheus-scaleway-sd

### ISSUE THREAD

**Issue by simonpasquier** [scaleway/prometheus-scw-sd#2]
This is a meta-issue describing how we could merge https://github.com/simonpasquier/prometheus-scaleway-sd into this repository. I'm more than happy to see this happening!

I had a quick look at the code and here are my initials remarks.

## Dealing with stopped/deleted servers

IIUC this project doesn't update the inventory when servers are stopped, deleted, etc. This could leave stale targets in the output file. In `prometheus-scaleway-sd`, I'm keeping track of the servers at each run so the SD application can notify servers that don't exist anymore.

https://github.com/simonpasquier/prometheus-scaleway-sd/blob/master/main.go#L217-L224

## Vendoring

I see that this repository doesn't vendor any dependency delegating it to the developer (cf. [README.md](https://github.com/scaleway/prometheus-scw-sd#contribute)).

I see a few problems here:
* The builds aren't fully reproducible since the dependencies can change at any point in time.
* The `github.com/prometheus/prometheus/discovery/manager` is copied in the repository. My guess is that it is to avoid pulling all SD dependencies (eg AWS, GCP, ... packages) but it also means that any fix to the `manager` package will have to be manually backported here.

## Logging

`prometheus-scaleway-sd` has a wrapper around `go-kit/log` to grab logs from the Scaleway API client. This may be useful for troubleshooting.

https://github.com/simonpasquier/prometheus-scaleway-sd/blob/master/main.go#L117-L146

## Instrumentation

`prometheus-scaleway-sd` exposes 2 metrics:
* `prometheus_scaleway_sd_request_duration_seconds`, histogram of latencies for requests to the Scaleway API.
* `prometheus_scaleway_sd_request_failures_total`, total number of failed requests to the Scaleway API.

Thanks to the `prometheus/client_golang`, it also expose process metrics.

## Security

As noted [here](https://github.com/prometheus/docs/pull/1135#issuecomment-409603627), the application shouldn't get the token from the command line, reading it from a file is fine.

## Release tooling

I've integrated with [promu](https://github.com/prometheus/promu) because it eases the generation of binaries across multiple platforms.

## Labels

They look more or less the same. No issue there.

**Comment by y0hnn** [comment]
Hello @simonpasquier,

Thanks for you review. What you have done is awesome.
As your project's code is not based on ours (not an initial fork), I see 2 options : 
1. You make a merge request in our repository, containing these changes
2. We try to merge the two repositories (resulting of course in a lot of copy / paste from your code)

As you already gave a lot of your time contributing to a service discovery for Scaleway, I'm not very confortable asking you to take some time again to prepare the MR. If you are OK with that, it would be perfect.
Else, I think the option 2 is more appropriate. We will do that on our side, and we will give you of course credits for what you've done (in the code headers, Readme, and adding you as a contributor in the project if you want to help maintaining this).

What do you think ? Do you agree with option 2, or do you have some time to submit a MR ?

Thanks again,

**Comment by simonpasquier** [comment]
Option 2 is fine for me. No problem for reviewing your PR and helping the project in the longer term.

**Comment by y0hnn** [comment]
Hello @simonpasquier, can you review #3 ? We credited you on the Readme. If this is ok to merge, we will create a new release after merging.
Thank you!
