### ISSUE TITLE
[request] docker image

### ISSUE THREAD

**Issue by sdurrheimer** [scaleway/prometheus-scw-sd#4]
It would be great to have an official docker image for this.

As the building process is Prometheus inspired using `promu`, the following `Dockerfile` should be a good start.
Don't know if this repo is handled by a CI/CD right now.

```Dockerfile
ARG ARCH="amd64"
ARG OS="linux"
FROM quay.io/prometheus/busybox-${OS}-${ARCH}:latest
LABEL maintainer="Scaleway <opensource@scaleway.com>"

ARG ARCH="amd64"
ARG OS="linux"
COPY .build/${OS}-${ARCH}/prometheus-scw-sd /bin/prometheus-scw-sd
COPY LICENSE                                /LICENSE

RUN mkdir -p /prometheus-scw-sd && \
    chown -R nobody:nogroup /prometheus-scw-sd

USER       nobody
EXPOSE     9465
VOLUME     [ "/prometheus-scw-sd" ]
WORKDIR    /prometheus-scw-sd
ENTRYPOINT [ "/bin/prometheus-scw-sd" ]
CMD        [ "--help" ]
```

**Comment by roidelapluie** [comment]
Could you try prom/prometheus:main ? Note that we lack some labels regarding to this project but I hope to get it to the same level by the time of the release.

**Comment by sdurrheimer** [comment]
Closing this issue as Prometheus as now native Scaleway discovery
